# Generated by Django 6.0.1 on 2026-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='applicants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('remote', 'عن بُعد'), ('hybrid', 'هجين')], max_length=20),
        ),
    ]
