# Generated by Django 6.0.1 on 2026-03-20 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobpost_applicants_count_jobpost_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_applicant', models.BooleanField(default=True)),
                ('notify_status_change', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
