# Generated by Django 6.0.1 on 2026-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companynotificationsettings_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
