# Generated by Django 6.0.1 on 2026-04-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotification',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='type',
            field=models.CharField(default='system', max_length=50),
        ),
    ]
