# Generated by Django 6.0.1 on 2026-05-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teachernotification_icon_teachernotification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
