# Generated by Django 6.0.1 on 2026-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_course_teacher_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
