# Generated by Django 6.0.1 on 2026-03-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_question_lessonprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_index']},
        ),
    ]
