# Generated by Django 6.0.1 on 2026-03-30 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teachernotification_teachernotificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_students', models.BooleanField(default=True)),
                ('notify_lessons', models.BooleanField(default=True)),
                ('notify_quizzes', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
