# Generated by Django 6.0.1 on 2026-04-02 00:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_teachersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/qr/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
